import cron from 'node-cron';
import fs from 'fs';
import path from 'path';
import { generateDailyUpdate } from '../tools/newsletter.js';
import { analyzeNewsletterContent } from '../tools/analytics.js';
import { sendNewsletterEmail } from '../email/sendEmail.js';
import { logInfo, logError } from '../logs/logger.js';

const configPath = path.join(process.cwd(), 'config', 'schedulerConfig.json');

export function startScheduler() {
    try {
        const configData = fs.readFileSync(configPath, 'utf8');
        const config = JSON.parse(configData);

        let cronExpression = '';

        if (config.mode === 'interval') {
            cronExpression = `*/${config.intervalMinutes} * * * *`;
            logInfo(`Scheduler configured for INTERVAL mode: every ${config.intervalMinutes} minutes.`);
        } else if (config.mode === 'daily') {
            const [hour, minute] = config.dailyTime.split(':');
            cronExpression = `${minute} ${hour} * * *`;
            logInfo(`Scheduler configured for DAILY mode: every day at ${config.dailyTime}.`);
        } else {
            throw new Error(`Invalid scheduler mode: ${config.mode}`);
        }

        logInfo(`Scheduler successfully started. Waiting for next run...`);

        cron.schedule(cronExpression, async () => {
            logInfo(`--- Triggering automated topic tracking update ---`);
            const topics = config.topics || (config.defaultTopic ? [config.defaultTopic] : []);
            
            for (const topic of topics) {
                logInfo(`Starting update pipeline for topic: "${topic}"`);
                await runAutomatedWorkflow(topic, config);
            }
            logInfo(`--- All topic updates completed ---`);
        });

    } catch (error) {
        logError(`Failed to start scheduler: ${error.message}`);
    }
}

export async function runAutomatedWorkflow(topic, config) {
    try {
        // 1. Generate Content
        logInfo(`[${topic}] Generating LLM daily update...`);
        const content = await generateDailyUpdate(topic);
        
        const safeTopicName = topic.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const outPath = path.join(process.cwd(), 'outputs', `auto-update-${safeTopicName}-${Date.now()}.md`);
        fs.writeFileSync(outPath, content);
        
        // 2. Analyze Content
        logInfo(`[${topic}] Calculating analytics...`);
        const analytics = analyzeNewsletterContent(content);
        
        const anPath = path.join(process.cwd(), 'analytics', `auto-analytics-${safeTopicName}-${Date.now()}.json`);
        fs.writeFileSync(anPath, JSON.stringify(analytics, null, 2));

        // 3. Prepare and Send Email
        if (config.emails && config.emails.length > 0) {
            logInfo(`[${topic}] Dispatching emails to ${config.emails.length} subscribers...`);
            
            const htmlContent = `
                <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
                    <h2 style="color: #2b6cb0;">📰 Daily Update: ${topic}</h2>
                    <div style="background: #edf2f7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                        <strong>📈 Quick Analytics:</strong><br>
                        ⏱️ Time to Read: ${analytics.readingTime}<br>
                        🧠 Sentiment: ${analytics.sentiment}<br>
                        🔑 Keywords: ${analytics.topKeywords.join(', ')}
                    </div>
                    <div style="border-top: 1px solid #e2e8f0; padding-top: 15px;">
                        <pre style="white-space: pre-wrap; font-family: sans-serif; line-height: 1.6;">${content}</pre>
                    </div>
                    <p style="font-size: 12px; color: #718096; margin-top: 30px;">
                        This email was automatically generated by the Intelligent Topic Tracking System.
                    </p>
                </div>
            `;
            
            const subject = `Daily Tracking: ${topic} - ${new Date().toLocaleDateString()}`;
            await sendNewsletterEmail(subject, htmlContent, config.emails);
        } else {
            logInfo(`[${topic}] No email subscribers configured. Skipping dispatch.`);
        }

        logInfo(`[${topic}] Workflow completed successfully.`);

    } catch (error) {
        logError(`[${topic}] Error during automated workflow: ${error.message}`);
    }
}
