import cron from 'node-cron';
import fs from 'fs';
import path from 'path';
import { generateNewsletterContent } from '../tools/newsletter.js';
import { analyzeNewsletterContent } from '../tools/analytics.js';
import { sendNewsletterEmail } from '../email/sendEmail.js';
import { logInfo, logError } from '../logs/logger.js';

const configPath = path.join(process.cwd(), 'config', 'schedulerConfig.json');

export function startScheduler() {
    try {
        const configData = fs.readFileSync(configPath, 'utf8');
        const config = JSON.parse(configData);

        let cronExpression = '';

        if (config.mode === 'interval') {
            cronExpression = `*/${config.intervalMinutes} * * * *`;
            logInfo(`Scheduler configured for INTERVAL mode: every ${config.intervalMinutes} minutes.`);
        } else if (config.mode === 'daily') {
            const [hour, minute] = config.dailyTime.split(':');
            cronExpression = `${minute} ${hour} * * *`;
            logInfo(`Scheduler configured for DAILY mode: every day at ${config.dailyTime}.`);
        } else {
            throw new Error(`Invalid scheduler mode: ${config.mode}`);
        }

        logInfo(`Scheduler successfully started. Waiting for next run...`);

        cron.schedule(cronExpression, async () => {
            logInfo(`--- Triggering automated newsletter generation ---`);
            logInfo(`Topic: "${config.defaultTopic}"`);
            await runAutomatedWorkflow(config);
        });

    } catch (error) {
        logError(`Failed to start scheduler: ${error.message}`);
    }
}

export async function runAutomatedWorkflow(config) {
    try {
        // 1. Generate Content
        logInfo('Generating LLM content...');
        const content = await generateNewsletterContent(config.defaultTopic);
        
        const outPath = path.join(process.cwd(), 'outputs', `auto-newsletter-${Date.now()}.md`);
        fs.writeFileSync(outPath, content);
        
        // 2. Analyze Content
        logInfo('Calculating analytics...');
        const analytics = analyzeNewsletterContent(content);
        
        const anPath = path.join(process.cwd(), 'analytics', `auto-analytics-${Date.now()}.json`);
        fs.writeFileSync(anPath, JSON.stringify(analytics, null, 2));

        // 3. Prepare and Send Email
        if (config.emails && config.emails.length > 0) {
            logInfo(`Dispatching emails to ${config.emails.length} subscribers...`);
            
            const htmlContent = `
                <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
                    <h2 style="color: #2b6cb0;">📰 AI Newsletter: ${config.defaultTopic}</h2>
                    <div style="background: #edf2f7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
                        <strong>📈 Quick Analytics:</strong><br>
                        ⏱️ Time to Read: ${analytics.readingTime}<br>
                        🧠 Sentiment: ${analytics.sentiment}<br>
                        🔑 Keywords: ${analytics.topKeywords.join(', ')}
                    </div>
                    <div style="border-top: 1px solid #e2e8f0; padding-top: 15px;">
                        <pre style="white-space: pre-wrap; font-family: sans-serif; line-height: 1.6;">${content}</pre>
                    </div>
                    <p style="font-size: 12px; color: #718096; margin-top: 30px;">
                        This email was automatically generated by the AI Newsletter MCP System.
                    </p>
                </div>
            `;
            
            const subject = `AI Newsletter - ${new Date().toLocaleDateString()}`;
            await sendNewsletterEmail(subject, htmlContent, config.emails);
        } else {
            logInfo('No email subscribers configured. Skipping dispatch.');
        }

        logInfo('--- Automated workflow completed successfully ---');

    } catch (error) {
        logError(`Error during automated workflow: ${error.message}`);
    }
}
